### ISSUE TITLE
SIGSEGV on high traffic in streaming

### ISSUE THREAD

**Issue by majestrate** [PurpleI2P/i2pd#1071]
something with the memory pool is causing this and I can't figure out what.

```0x00005555556d40f7 in i2p::util::MemoryPool<i2p::stream::Packet>::Acquire<>() (this=0x7fffe9840800) at libi2pd/util.h:58
58                                              m_Head = static_cast<T*>(*(void * *)m_Head); // next
>>> bt
#0  0x00005555556d40f7 in i2p::util::MemoryPool<i2p::stream::Packet>::Acquire<>() (this=0x7fffe9840800) at libi2pd/util.h:58
#1  0x00005555556d35f2 in i2p::stream::StreamingDestination::NewPacket (this=0x7fffe9840610) at libi2pd/Streaming.h:280
#2  0x00005555556d13aa in i2p::stream::StreamingDestination::HandleDataMessagePayload (this=0x7fffe9840610, buf=0x7fffea8680c3 "\037\213\b", len=1777) at libi2pd/Streaming.cpp:1143
#3  0x000055555567cba5 in i2p::client::ClientDestination::HandleDataMessage (this=0x7fffeb8ab810, buf=0x7fffea8680c3 "\037\213\b", len=1781) at libi2pd/Destination.cpp:869
#4  0x0000555555678d27 in i2p::client::LeaseSetDestination::HandleI2NPMessage (this=0x7fffeb8ab810, buf=0x7fffea8680af "\024\214\215mQ", len=1827, from=std::shared_ptr (count 13, w
eak 1) 0x7fffea81b2d0) at libi2pd/Destination.cpp:328
#5  0x000055555564e7f0 in i2p::garlic::GarlicDestination::HandleGarlicPayload (this=0x7fffeb8ab810, buf=0x7fffea8680af "\024\214\215mQ", len=1860, from=std::shared_ptr (count 13, w
eak 1) 0x7fffea81b2d0) at libi2pd/Garlic.cpp:557  ```

**Comment by orignal** [comment]
Try without it

**Comment by majestrate** [comment]
works fine when not using the memory pool

**Comment by orignal** [comment]
then temporary disable it and commit, however we need to investigate. Race condition may be
