### ISSUE TITLE
SEGV related to SAM

### ISSUE THREAD

**Issue by radfish** [PurpleI2P/i2pd#1123]
2.18.0.r52.gf2a14047

```
Core was generated by `/usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --pidfile=/var/run/i2pd/i2pd.pid --da'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x006f64d8 in i2p::stream::Stream::ConcatenatePackets(unsigned char*, unsigned int) ()
[Current thread is 1 (Thread 0xae4ff450 (LWP 22712))]
(gdb) bt
#0  0x006f64d8 in i2p::stream::Stream::ConcatenatePackets(unsigned char*, unsigned int) ()
#1  0x00733c88 in i2p::client::SAMSocket::I2PReceive() ()
#2  0x00734738 in i2p::client::SAMSocket::HandleI2PReceive(boost::system::error_code const&, unsigned int) ()
#3  0x00736f0c in void i2p::stream::Stream::HandleReceiveTimer<boost::asio::mutable_buffers_1, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)> >(boost::system::error_code const&, boost::asio::mutable_buffers_1 const&, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)>, int) ()
#4  0x00739130 in boost::asio::detail::wait_handler<void i2p::stream::Stream::AsyncReceive<boost::asio::mutable_buffers_1, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)> >(boost::asio::mutable_buffers_1 const&, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)>, int)::{lambda()#1}::operator()() const::{lambda(boost::system::error_code const&)#1}>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#5  0x006688a4 in i2p::client::LeaseSetDestination::Run() ()
#6  0xb6aeb518 in std::execute_native_thread_routine (__p=0xefd5f8) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#7  0xb69faee4 in start_thread () from /usr/lib/libpthread.so.0
#8  0xb6982328 in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

**Comment by majestrate** [comment]
yeah, related to streaming's packet pool i suspect.

**Comment by radfish** [comment]
One more:
```
#0  0x005bdce4 in boost::asio::detail::epoll_reactor::deregister_descriptor(int, boost::asio::detail::epoll_reactor::descriptor_state*&, bool) ()
#1  0x005bf074 in boost::asio::basic_socket<boost::asio::ip::tcp>::close() ()
#2  0x00720cf8 in i2p::client::SAMSocket::Terminate(char const*) ()
#3  0x00725bc0 in i2p::client::SAMSocket::I2PReceive() ()
#4  0x00726658 in i2p::client::SAMSocket::HandleI2PReceive(boost::system::error_code const&, unsigned int) ()
#5  0x00728eac in void i2p::stream::Stream::HandleReceiveTimer<boost::asio::mutable_buffers_1, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)> >(boost::system::error_code const&, boost::asio::mutable_buffers_1 const&, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)>, int) ()
#6  0x0072b0d0 in boost::asio::detail::wait_handler<void i2p::stream::Stream::AsyncReceive<boost::asio::mutable_buffers_1, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)> >(boost::asio::mutable_buffers_1 const&, std::_Bind<void (i2p::client::SAMSocket::*(std::shared_ptr<i2p::client::SAMSocket>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned int)>, int)::{lambda()#1}::operator()() const::{lambda(boost::system::error_code const&)#1}>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#7  0x0065a05c in i2p::client::LeaseSetDestination::Run() ()
#8  0xb6b4c518 in std::execute_native_thread_routine (__p=0xb350dd80) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#9  0xb6a5bee4 in start_thread () from /usr/lib/libpthread.so.0
#10 0xb69e3328 in ?? () from /usr/lib/libc.so.6
```

**Comment by r4sas** [comment]
status?

**Comment by radfish** [comment]
Must have been fixed. I have been downloading several torrents fine. Before, downloading torrents from i2p trackers did not work at all. Now everything works, and no more crash.
