### ISSUE TITLE
[SAM] SIGSEGV on Stop

### ISSUE THREAD

**Issue by r4sas** [PurpleI2P/i2pd#1233]
OS: Windows
```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000009a4a23 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) ()
    at C:/msys64/mingw64/include/c++/7.3.0/bits/stl_construct.h:75
75          { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
(gdb) bt full
#0  0x00000000009a4a23 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) ()
    at C:/msys64/mingw64/include/c++/7.3.0/bits/stl_construct.h:75
No symbol table info available.
#1  0x00000000008d7c5b in std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<i2p::client::SAMSession> > >::operator++ (this=0x23fcd8)
    at C:/msys64/mingw64/include/c++/7.3.0/bits/stl_tree.h:287
No locals.
#2  0x00000000004c4fdd in i2p::client::SAMBridge::Stop (this=0xb921dd0)
    at libi2pd_client/SAM.cpp:946
        it = @0xa999600: {first = {static npos = 18446744073709551615,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0xfeeefeeefeeefeee <error: Cannot access memory at address 0xfeeefeeefeeefeee>}, _M_string_length = 18369900232523579118, {
              _M_local_buf = "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
              _M_allocated_capacity = 18369900232523579118}},
          second = {<std::__shared_ptr<i2p::client::SAMSession, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<i2p::client::SAMSession, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>},
              _M_ptr = 0xfeeefeeefeeefeee, _M_refcount = {
                _M_pi = 0xfeeefeeefeeefeee}}, <No data fields>}}
        __for_range = @0xb921f08: {_M_t = {
            _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<i2p::client::SAMSession> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<i2p::client::SAMSession> > > >> = {<No data fields>}, <No data fields>}, <std::_Rb_tree_key_compare<std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
                _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}}, <std::_Rb_tree_header> = {_M_header = {
                  _M_color = std::_S_red, _M_parent = 0xb0f0c70,
                  _M_left = 0xb0f0c70, _M_right = 0xb0f0c70},
                _M_node_count = 1}, <No data fields>}}}
        __for_begin = {_M_node = 0xa9995e0}
        __for_end = {_M_node = 0xb921f10}
#3  0x00000000004a8b52 in i2p::client::ClientContext::Stop (
    this=0xbf8ba0 <i2p::client::context>)
    at libi2pd_client/ClientContext.cpp:145
No locals.
#4  0x00000000004158e2 in i2p::util::Daemon_Singleton::stop (
    this=0x9e4480 <i2p::util::DaemonWin32::Instance()::instance>)
    at daemon/Daemon.cpp:350
No locals.
#5  0x00000000004164cf in i2p::util::DaemonWin32::stop (
    this=0x9e4480 <i2p::util::DaemonWin32::Instance()::instance>)
    at Win32/DaemonWin32.cpp:97
No locals.
#6  0x00000000004015f2 in main (argc=1, argv=0x72f4f80) at daemon/i2pd.cpp:27
No locals.
```

**Comment by r4sas** [comment]
Happens only when works Anoncoin.

**Comment by r4sas** [comment]
Singlethread SAM was introduced, so closing for now.
