### ISSUE TITLE
BOB fails to create inbound tunnel

### ISSUE THREAD

**Issue by rszibele** [PurpleI2P/i2pd#1357]
The connection gets closed when you try to create an inbound tunnel and there is an error in the stdout/stderr of i2pd.

```
$ nc localhost 2827
BOB 00.00.10
OK
setnick test-source
OK Nickname set to test-source
newkeys
OK HnN2n3wK78pVRfNInYJsRMYwrOu-G7i1tFWIHIsnSpNzLltRdgDjbH3vMk0KkkaR0s0DX3r~P-U~NR6H5ekDx5SP2~qGPKc4KykWQttCmJkaY5gRc5mMtCviHL8Vx6ilgh0ttQ0PMhAsIDjPac2O8jK4ccqWF2ufS8IGOCEUKIyCNA8zq85-VeJH-6f0n~5jjihaMofaam7J31IOoZgREBoN9K70fTTjURrogNFoJXyZKC3qAnvhwjQmx12NdnwmwKZxRlKq7l421e6dE4Y7z~kshMiQizsYBEQimAQRzPw0gVYGwFe59fP0kZYa21xDjsFn82XxiKg9tkGr78LpcREs15uncN0ZmFE7NNBlrDzyT~SzTf4mfSBq7fcII30ePVHWiNNfo0R09oknyZF~-okQzqK1AV2qjxNxi7~JaDnNAsOAuu4g1TdIGjLho4uREbR35jcyeC0CYhfEzvHMmTTTCB-H3LTfCMdeDATFIbUxAN0HjnZNV-x5HCJ5jdtxAAAA
outhost localhost 
OK outhost set
outport 33555
OK outbound port set
start
```
i2pd output:
```09:20:16@223/error - BOB: runtime exception: Invalid argument```

I also created an outbound tunnel and tried to connect to it but it fails with destination not found.

**Comment by rszibele** [comment]
caused by:
https://github.com/PurpleI2P/i2pd/blob/07405e57b97865e2b68f6411b27ffb67e7079149/libi2pd_client/BOB.cpp#L206

from_string docs:
> Create an address from an IPv4 address string in dotted decimal form, or from an IPv6 address in hexadecimal notation.

A resolver would need to be used to support this:
https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve.html

gdb backtrace:
```gdb
#0  0x00007ffff7a2c3ce in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555c60c92 in boost::throw_exception<boost::system::system_error> (e=...) at /usr/include/boost/throw_exception.hpp:69
#2  0x0000555555c5ebd5 in boost::asio::detail::do_throw_error (err=...) at /usr/include/boost/asio/detail/impl/throw_error.ipp:32
#3  0x0000555555c5e9a1 in boost::asio::detail::throw_error (err=...) at /usr/include/boost/asio/detail/throw_error.hpp:35
#4  0x0000555555c7e36c in boost::asio::ip::make_address (str=0x5555564b44b0 "localhost")
    at /usr/include/boost/asio/ip/impl/address.ipp:108
#5  0x0000555555c7e48b in boost::asio::ip::make_address (str="localhost") at /usr/include/boost/asio/ip/impl/address.ipp:129
#6  0x0000555555c7e286 in boost::asio::ip::address::from_string (str="localhost") at /usr/include/boost/asio/ip/impl/address.hpp:43
#7  0x0000555555fb2a69 in i2p::client::BOBI2POutboundTunnel::BOBI2POutboundTunnel (this=0x7fffc4005f90, address="localhost", 
    port=33555, localDestination=std::shared_ptr<class i2p::client::ClientDestination> (use count 8, weak count 1) = {...}, 
    quiet=false) at /home/richard/Documents/i2pd/libi2pd_client/BOB.cpp:124
#8  0x0000555555fb32a9 in i2p::client::BOBDestination::CreateOutboundTunnel (this=0x7fffc400b1e0, address="localhost", port=33555, 
    quiet=false) at /home/richard/Documents/i2pd/libi2pd_client/BOB.cpp:239
#9  0x0000555555fb411b in i2p::client::BOBCommandSession::StartCommandHandler (this=0x5555564b3c30, operand=0x5555564b3c6d "", len=0)
    at /home/richard/Documents/i2pd/libi2pd_client/BOB.cpp:427
#10 0x0000555555fb384c in i2p::client::BOBCommandSession::HandleReceived (this=0x5555564b3c30, ecode=..., bytes_transferred=6)
    at /home/richard/Documents/i2pd/libi2pd_client/BOB.cpp:294
#11 0x0000555555fc66c9 in std::__invoke_impl<void, void (i2p::client::BOBCommandSession::*&)(boost::system::error_code const&, unsigned long), std::shared_ptr<i2p::client::BOBCommandSession>&, boost::system::error_code const&, unsigned long const&> (__f=
    @0x7fffe3ffeaa0: (void (i2p::client::BOBCommandSession::*)(class i2p::client::BOBCommandSession * const, const class boost::system::error_code &, unsigned long)) 0x555555fb35f6 <i2p::client::BOBCommandSession::HandleReceived(boost::system::error_code const&, unsigned long)>, __t=std::shared_ptr<class i2p::client::BOBCommandSession> (use count 1, weak count 1) = {...}, __args#0=..., 
    __args#1=@0x7fffe3ffead0: 6) at /usr/include/c++/8/bits/invoke.h:73
#12 0x0000555555fc6228 in std::__invoke<void (i2p::client::BOBCommandSession::*&)(boost::system::error_code const&, unsigned long), std::shared_ptr<i2p::client::BOBCommandSession>&, boost::system::error_code const&, unsigned long const&> (__fn=
    @0x7fffe3ffeaa0: (void (i2p::client::BOBCommandSession::*)(class i2p::client::BOBCommandSession * const, const class boost::system::error_code &, unsigned long)) 0x555555fb35f6 <i2p::client::BOBCommandSession::HandleReceived(boost::system::error_code const&, unsigned long)>, __args#0=std::shared_ptr<class i2p::client::BOBCommandSession> (use count 1, weak count 1) = {...}, __args#1=..., 
    __args#2=@0x7fffe3ffead0: 6) at /usr/include/c++/8/bits/invoke.h:95
#13 0x0000555555fc5df5 in std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::__call<void, boost::system::error_code const&, unsigned long const&, 0ul, 1ul, 2ul>(std::tuple<boost::system::error_code const&, unsigned long const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x7fffe3ffeaa0, __args=...) at /usr/include/c++/8/functional:400
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x0000555555fc5a51 in std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::operator()<boost::system::error_code const&, unsigned long const&, void>(boost::system::error_code const&, unsigned long const&) (this=0x7fffe3ffeaa0, __args#0=..., 
    __args#1=@0x7fffe3ffead0: 6) at /usr/include/c++/8/functional:484
#15 0x0000555555fc5577 in boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long>::operator()() (this=0x7fffe3ffeaa0) at /usr/include/boost/asio/detail/bind_handler.hpp:164
#16 0x0000555555fc48ee in boost::asio::asio_handler_invoke<boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long>&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#17 0x0000555555fc3bac in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long>, std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)> >(boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long>&, std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>&) (function=..., context=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#18 0x0000555555fc2959 in boost::asio::detail::handler_work<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::asio::system_executor>::complete<boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, boost::system::error_code, unsigned long>&, std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>&) (this=0x7fffe3ffea76, function=..., handler=...)
    at /usr/include/boost/asio/detail/handler_work.hpp:82
#19 0x0000555555fc0c00 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::_Bind<void (i2p::client::BOBCommandSession::*(std::shared_ptr<i2p::client::BOBCommandSession>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned--Type <RET> for more, q to quit, c to continue without paging--
 long) (owner=0x5555564b3270, base=0x7fffc4001960) at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:122
#20 0x0000555555c783b4 in boost::asio::detail::scheduler_operation::complete (this=0x7fffc4001960, owner=0x5555564b3270, ec=..., 
    bytes_transferred=0) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#21 0x0000555555c7b015 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete (owner=0x5555564b3270, 
    base=0x7fffc4000b20, ec=..., bytes_transferred=1) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:776
#22 0x0000555555c783b4 in boost::asio::detail::scheduler_operation::complete (this=0x7fffc4000b20, owner=0x5555564b3270, ec=..., 
    bytes_transferred=1) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#23 0x0000555555c7bbcc in boost::asio::detail::scheduler::do_run_one (this=0x5555564b3270, lock=..., this_thread=..., ec=...)
    at /usr/include/boost/asio/detail/impl/scheduler.ipp:401
#24 0x0000555555c7b69b in boost::asio::detail::scheduler::run (this=0x5555564b3270, ec=...)
    at /usr/include/boost/asio/detail/impl/scheduler.ipp:154
#25 0x0000555555c7bed2 in boost::asio::io_context::run (this=0x5555564b3180) at /usr/include/boost/asio/impl/io_context.ipp:62
#26 0x0000555555fb701c in i2p::client::BOBCommandChannel::Run (this=0x5555564b3170)
    at /home/richard/Documents/i2pd/libi2pd_client/BOB.cpp:753
#27 0x0000555555fc40a8 in std::__invoke_impl<void, void (i2p::client::BOBCommandChannel::*&)(), i2p::client::BOBCommandChannel*&> (
    __f=@0x55555622e098: (void (i2p::client::BOBCommandChannel::*)(class i2p::client::BOBCommandChannel * const)) 0x555555fb6fe6 <i2p::client::BOBCommandChannel::Run()>, __t=@0x55555622e0a8: 0x5555564b3170) at /usr/include/c++/8/bits/invoke.h:73
#28 0x0000555555fc2e56 in std::__invoke<void (i2p::client::BOBCommandChannel::*&)(), i2p::client::BOBCommandChannel*&> (
    __fn=@0x55555622e098: (void (i2p::client::BOBCommandChannel::*)(class i2p::client::BOBCommandChannel * const)) 0x555555fb6fe6 <i2p::client::BOBCommandChannel::Run()>, __args#0=@0x55555622e0a8: 0x5555564b3170) at /usr/include/c++/8/bits/invoke.h:95
#29 0x0000555555fc14a1 in std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x55555622e098, __args=...) at /usr/include/c++/8/functional:400
#30 0x0000555555fbf11b in std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>::operator()<, void>() (this=0x55555622e098) at /usr/include/c++/8/functional:484
#31 0x0000555555fbce8b in std::__invoke_impl<void, std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>>(std::__invoke_other, std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>&&) (__f=...)
    at /usr/include/c++/8/bits/invoke.h:60
#32 0x0000555555fba942 in std::__invoke<std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>>(std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()>&&) (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#33 0x0000555555fc6e0a in std::thread::_Invoker<std::tuple<std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555622e098) at /usr/include/c++/8/thread:244
#34 0x0000555555fc6d53 in std::thread::_Invoker<std::tuple<std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()> > >::operator()() (this=0x55555622e098) at /usr/include/c++/8/thread:253
--Type <RET> for more, q to quit, c to continue without paging--
#35 0x0000555555fc6ca8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (i2p::client::BOBCommandChannel::*(i2p::client::BOBCommandChannel*))()> > > >::_M_run() (this=0x55555622e090) at /usr/include/c++/8/thread:196
#36 0x00007ffff7a57420 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#37 0x00007ffff7955182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#38 0x00007ffff787eb1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by orignal** [comment]
you can't use any addresss strings, you must use 127.0.0.1 in your case.
