### ISSUE TITLE
i2pd_qt: RSA signing key type 4 is not supported - crash during execution

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1445]
```
(gdb) bt full
#0  0x000056181df40614 in ?? ()
No symbol table info available.
#1  0x00007f65f40348d4 in ?? ()
No symbol table info available.
#2  0x0000033411ffa850 in ?? ()
No symbol table info available.
#3  0x00007f65f40345a0 in ?? ()
No symbol table info available.
#4  0x00007f661457e658 in ?? ()
No symbol table info available.
#5  0x00007f6611ffa820 in ?? ()
No symbol table info available.
#6  0x000056181dec2aa1 in ?? ()
No symbol table info available.
#7  0x00007f65f40348d4 in ?? ()
No symbol table info available.
#8  0x000003341deef094 in ?? ()
No symbol table info available.
#9  0x00007f65f40345a0 in ?? ()
No symbol table info available.
#10 0x00007f661457e2f0 in ?? ()
No symbol table info available.
#11 0x00007f6611ffa8a0 in ?? ()
No symbol table info available.
#12 0x000056181dedecb5 in ?? ()
No symbol table info available.
#13 0x00007f6611ffa8d0 in ?? ()
No symbol table info available.
#14 0x00007f661457e2f0 in ?? ()
No symbol table info available.
#15 0x00007f65f41416f0 in ?? ()
No symbol table info available.
#16 0x0000000111ffa88f in ?? ()
No symbol table info available.
#17 0x00007f65f4060640 in ?? ()
No symbol table info available.
#18 0x00007f65f4060630 in ?? ()
No symbol table info available.
#19 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 
```

это началось когда добавил такой туннель в tunnels.conf:

```
[x1]
type=client
address=127.0.0.1
port=12370
destination=irc.ilita.i2p
destinationport=6667
signaturetype=1
keys=transient
```

**Comment by nonlinear-chaos-order-etc** [comment]
another run : 

```
(gdb) bt full
#0  0x000056181df40614 in ?? ()
No symbol table info available.
#1  0x00007f65f40348d4 in ?? ()
No symbol table info available.
#2  0x0000033411ffa850 in ?? ()
No symbol table info available.
#3  0x00007f65f40345a0 in ?? ()
No symbol table info available.
#4  0x00007f661457e658 in ?? ()
No symbol table info available.
#5  0x00007f6611ffa820 in ?? ()
No symbol table info available.
#6  0x000056181dec2aa1 in ?? ()
No symbol table info available.
#7  0x00007f65f40348d4 in ?? ()
No symbol table info available.
#8  0x000003341deef094 in ?? ()
No symbol table info available.
#9  0x00007f65f40345a0 in ?? ()
No symbol table info available.
#10 0x00007f661457e2f0 in ?? ()
No symbol table info available.
#11 0x00007f6611ffa8a0 in ?? ()
No symbol table info available.
#12 0x000056181dedecb5 in ?? ()
No symbol table info available.
#13 0x00007f6611ffa8d0 in ?? ()
No symbol table info available.
#14 0x00007f661457e2f0 in ?? ()
No symbol table info available.
#15 0x00007f65f41416f0 in ?? ()
No symbol table info available.
#16 0x0000000111ffa88f in ?? ()
No symbol table info available.
#17 0x00007f65f4060640 in ?? ()
No symbol table info available.
#18 0x00007f65f4060630 in ?? ()
No symbol table info available.
#19 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 
```

posting debug log at pastebin

**Comment by nonlinear-chaos-order-etc** [comment]
debug loglevel log tail from last run:

```
18:42:53@717/info - i2pd v2.28.0 starting
18:42:53@717/debug - FS: main config file: /home/user/.i2pd/i2pd.conf
18:42:53@717/debug - FS: data directory: /home/user/.i2pd
18:42:53@717/info - Daemon: accepting incoming connections at port 0
[...]
18:43:49@526/debug - NTCP2: received length 1072
18:43:49@526/debug - NTCP2: received message decrypted
18:43:49@526/debug - NTCP2: Block type 3 of size 1037
18:43:49@526/debug - NTCP2: I2NP
18:43:49@526/debug - NTCP2: Block type 254 of size 13
18:43:49@526/debug - NTCP2: padding
18:43:49@526/debug - NTCP2: received length 1123
18:43:49@526/debug - NTCP2: received message decrypted
18:43:49@526/debug - NTCP2: Block type 3 of size 1037
18:43:49@526/debug - NTCP2: I2NP
18:43:49@526/debug - NTCP2: Block type 254 of size 64
18:43:49@526/debug - NTCP2: padding
18:43:50@526/debug - NTCP2: received length 1120
18:43:50@526/debug - NTCP2: received message decrypted
18:43:50@526/debug - NTCP2: Block type 3 of size 1037
18:43:50@526/debug - NTCP2: I2NP
18:43:50@526/debug - NTCP2: Block type 254 of size 61
18:43:50@526/debug - NTCP2: padding
18:43:50@526/debug - NTCP2: received length 1094
18:43:50@526/debug - NTCP2: received message decrypted
18:43:50@526/debug - NTCP2: Block type 3 of size 1037
18:43:50@526/debug - NTCP2: I2NP
18:43:50@526/debug - NTCP2: Block type 254 of size 35
18:43:50@526/debug - NTCP2: padding
18:43:52@796/info - Garlic: No tags available, will use ElGamal
18:43:52@526/debug - NTCP2: sent length 2105
18:43:52@526/debug - NTCP2: Next frame sent 2107
18:43:53@585/error - Identity: couldn't get verifier in 5 seconds
18:43:53@585/error - Identity: RSA signing key type 4 is not supported
```

**Comment by nonlinear-chaos-order-etc** [comment]
another run's crash log tail:

```
18:57:30@634/info - NTCP2: Connect error Нет маршрута до узла
18:57:30@634/debug - NTCP2: Couldn't shutdown socket: Конечная точка передачи не подсоединена
18:57:30@634/debug - NTCP2: session terminated
18:57:30@270/debug - Transports: NTCP address is not present for Qhpc, trying SSU
18:57:30@270/info - Transports: No NTCP or SSU addresses available
18:57:32@554/error - Identity: couldn't get verifier in 5 seconds
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
< > R4SAS, да, это фикснуто
< > это был sigtype 4 в нетдб в одной ri
< > закрываю

**Comment by nonlinear-chaos-order-etc-etal** [comment]
```
<R4SAS> orignal: это же уже пофикшено? https://github.com/PurpleI2P/i2pd/issues/1445
<R4SAS> хотя это чет странное
<orignal> а x3
<BreakCoreTimes> orignal, не хз
<BreakCoreTimes> надо наверное на sigtype 4 материться проверку вставить?
<R4SAS> так делали же вроде что то
<BreakCoreTimes> просто ri удалили
<BreakCoreTimes> и всё заработало
<BreakCoreTimes> это у меня от старых и2пд остался ri
<R4SAS> так подсуть опять
<R4SAS> подсунь*
<BreakCoreTimes> ну удалил, не сохранил
<BreakCoreTimes> R4SAS, надо вот в это место другой обработчик наверна
<BreakCoreTimes> 18:43:53@585/error - Identity: RSA signing key type 4 is not supported

**Comment by r4sas** [comment]
related: https://github.com/PurpleI2P/i2pd/issues/1451
