### ISSUE TITLE
[i2pd_qt] Another obscure crash (on Restart button pressed)

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1448]
flatpak run website.i2pd.i2pd : 

/app/bin/i2pd_qt_wrapper: строка 10:     3 Ошибка сегментирования                   (стек памяти сброшен на диск) i2pd_qt --datadir=$XDG_DATA_HOME/.i2pd

(gdb) bt full
#0  0x00007fce39051e97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

при нажатии на btn Restart -> [Restart i2pd] после редактирования в туннеле (заменил "irc-keys.dat" на "transient") и изменения параметров General Log stdout -> file, и изменения имени лог файла.

flatpak info website.i2pd.i2pd
Ref: app/website.i2pd.i2pd/x86_64/stable
ID: website.i2pd.i2pd
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2019-08-28 09:31:58 +0000
Subject: Update to 2.28.0 (880bfbc9)
Commit: 114ec428fa4260b41b2c81da635391c9af511e5ea1a0194f863dc33b4ff791d2
Parent: ee3942d1499d5fb0b1048a3de2d427966f49eb00fd6cd81c37d8ae90373f6170
Location: /var/lib/flatpak/app/website.i2pd.i2pd/x86_64/stable/114ec428fa4260b41b2c81da635391c9af511e5ea1a0194f863dc33b4ff791d2
Installed size: 130,4 МБ
Runtime: org.kde.Platform/x86_64/5.12
Sdk: org.kde.Sdk/x86_64/5.12

**Comment by nonlinear-chaos-order-etc-etal** [comment]
```
<BreakCoreTimes> 1448 - рестарт в 0.28 вообще глючит недетски, надо разбираться
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
It seems doesn't trigger anymore.
