### ISSUE TITLE
docs bugs: android build instr: 1. java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema + 2. gradle targets + 3. boost branch + 4. openssl 1.1.1d

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1541]
https://i2pd.readthedocs.io/en/latest/devs/building/android/

```
./tools/bin/sdkmanager "build-tools;25.0.3" "platforms;android-14" "platforms;android-25" "platform-tools"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
```
java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
when java 8, the same exception:

```
java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Server VM (build 25.231-b11, mixed mode)
```
./tools/bin/sdkmanager "build-tools;25.0.3" "platforms;android-14" "platforms;android-25" "platform-tools"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
```
echo $JAVA_HOME

Ok
echo $JAVAHOME

Ok
echo $JDKHOME

Ok
echo $JDK_HOME

Ok

```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Downloading via AS SDKMAN:

```
Packages to install: 
- Android SDK Build-Tools 30 (build-tools;30.0.0)
- NDK (Side by side) 21.3.6528147 (ndk;21.3.6528147)

Preparing "Install Android SDK Build-Tools 30 (revision: 30.0.0)".
Downloading https://dl.google.com/android/repository/build-tools_r30-linux.zip
"Install Android SDK Build-Tools 30 (revision: 30.0.0)" ready.
Preparing "Install NDK (Side by side) 21.3.6528147 (revision: 21.3.6528147)".
Downloading https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
```

[edits of this comment: pending; saving comment for now]

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Additional notes:

`./gradlew clean cleanBuildCache assembleDebug` instead of `gradle clean assembleDebug`

**Comment by nonlinear-chaos-order-etc-etal** [comment]
3.
`git clone https://github.com/PurpleI2P/Boost-for-Android-Prebuilt.git -b boost-1_72_0` instead of `git clone https://github.com/PurpleI2P/Boost-for-Android-Prebuilt.git`

**Comment by nonlinear-chaos-order-etc-etal** [comment]
4. openssl 1.1.1d needed, not 1.1.1a

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Downloaded the latest commandlinetools SDK.

```
Warning: Could not create settings
java.lang.IllegalArgumentException
```

Solved by https://stackoverflow.com/a/61176718/529442 : 

```
unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
./cmdline-tools/tools/bin/sdkmanager "build-tools;25.0.3" "platforms;android-14" "platforms;android-25" "platform-tools"
```
