### ISSUE TITLE
Error of null length tunnel. Ошибка нулевого туннеля.

### ISSUE THREAD

**Issue by wipedlifepotato** [PurpleI2P/i2pd#1557]
https://privetalena.ru/btfull.html
```
(gdb) bt full
#0  i2p::CreateTunnelGatewayMsg (tunnelID=3193695706, msg=std::shared_ptr (empty) = {...})
    at libi2pd/I2NPProtocol.cpp:548
No locals.
#1  0x000055555561a6ba in i2p::tunnel::ZeroHopsOutboundTunnel::SendTunnelDataMsg (this=0x7fffb001bf40,
    msgs=std::vector of length 1, capacity 1 = {...}) at libi2pd/Tunnel.cpp:312
        msg = @0x7fffa8006680: {deliveryType = i2p::tunnel::eDeliveryTypeTunnel, hash = {{
              m_Buf = "\240\024\251?\266\006\061\241\177\220\300R\202\242-\267\265tV\216,\255\334\372C\300Шњ\270?xo", ll = {
                11615072293787079840, 13199384763510591615, 18076513411236525237, 8032239997553262659}}}, tunnelID = 3193695706,
          data = std::shared_ptr (empty) = {get() = 0x0}}
        __for_range = std::vector of length 1, capacity 1 = {{deliveryType = i2p::tunnel::eDeliveryTypeTunnel, hash = {{
                m_Buf = "\240\024\251?\266\006\061\241\177\220\300R\202\242-\267\265tV\216,\255\334\372C\300Шњ\270?xo", ll = {
                  11615072293787079840, 13199384763510591615, 18076513411236525237, 8032239997553262659}}}, tunnelID = 3193695706,
            data = std::shared_ptr (empty) = {get() = 0x0}}}
        __for_begin =
    {deliveryType = i2p::tunnel::eDeliveryTypeTunnel, hash = {{m_Buf = "\240\024\251?\266\006\061\241\177\220\300R\202\242-\267\265tV\216,\255\334\372C\300Шњ\270?xo", ll = {11615072293787079840, 13199384763510591615, 18076513411236525237, 8032239997553262659}}}, tunnelID = 3193695706, data = std::shared_ptr (empty) = {get() = 0x0}}
        __for_end =
    {deliveryType = i2p::tunnel::eDeliveryTypeLocal, hash = {{m_Buf = "\000\000\000\000\000\000\000\000`\000\000\000\000\000\000\000\025\001\000\000\000\000\000\000\000k\002\250\377\177\000", ll = {0, 96, 277, 140736012118784}}}, tunnelID = 2818574544, data = std::shared_ptr (empty) = {get() = 0x0}}
#2  0x00005555557a9a7a in i2p::stream::Stream::SendPackets (this=0x7fffa8014b60, packets=std::vector of length 1, capacity 1 = {...})
    at libi2pd/Streaming.cpp:800
        msgs = std::vector of length 1, capacity 1 = {{deliveryType = i2p::tunnel::eDeliveryTypeTunnel, hash = {{
                m_Buf = "\240\024\251?\266\006\061\241\177\220\300R\202\242-\267\265tV\216,\255\334\372C\300Шњ\270?xo", ll = {
                  11615072293787079840, 13199384763510591615, 18076513411236525237, 8032239997553262659}}}, tunnelID = 3193695706,
            data = std::shared_ptr (empty) = {get() = 0x0}}}
        ts = 1602437155072
#3  0x00005555557aa385 in i2p::stream::Stream::HandleResendTimer (this=0x7fffa8014b60, ecode=...) at libi2pd/Streaming.cpp:900
        ts = 1602437155072
        packets = std::vector of length 1, capacity 1 = {0x7fffa8001900}
#4  0x00005555557c3699 in std::__invoke_impl&, boost::system::error_code const&> (__f=
    @0x7fffdf7fdb30: (void (i2p::stream::Stream::*)(i2p::stream::Stream * const, const boost::system::error_code &)) 0x5555557a9ee8 ,
    __t=std::shared_ptr (use count 4, weak count 1) = {...}, __args#0=...) at /usr/include/c++/8/bits/invoke.h:73
No locals.
#5  0x00005555557c3527 in std::__invoke&, boost::system::error_code const&> (__fn=
    @0x7fffdf7fdb30: (void (i2p::stream::Stream::*)(i2p::stream::Stream * const, const boost::system::error_code &)) 0x5555557a9ee8 ,
    __args#0=std::shared_ptr (use count 4, weak count 1) = {...}, __args#1=...) at /usr/include/c++/8/bits/invoke.h:95
No locals.
#6  0x00005555557c3297 in std::_Bind, std::_Placeholder<1>))(boost::system::error_code const&)>::__call(std::tuple&&, std::_Index_tuple<0ul, 1ul>) (this=0x7fffdf7fdb30, __args=...) at /usr/include/c++/8/functional:400
No locals.
#7  0x00005555557c2ed7 in std::_Bind, std::_Placeholder<1>))(boost::system--Type  for more, q to quit, c to continue without paging--
::error_code const&)>::operator()(boost::system::error_code const&) (this=0x7fffdf7fdb30,
    __args#0=...) at /usr/include/c++/8/functional:484
No locals.
#8  0x00005555557c2721 in boost::asio::detail::binder1, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code>::operator()() (this=0x7fffdf7fdb30)
    at /usr/include/boost/asio/detail/bind_handler.hpp:65
No locals.
#9  0x00005555557c1cc7 in boost::asio::asio_handler_invoke, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code> >(boost::asio::detail::binder1, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code>&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
No locals.
#10 0x00005555557c0bf1 in boost_asio_handler_invoke_helpers::invoke, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code>, std::_Bind, std::_Placeholder<1>))(boost::system::error_code const&)> >(boost::asio::detail::binder1, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code>&, std::_Bind, std::_Placeholder<1>))(boost::system::error_code const&)>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
No locals.
#11 0x00005555557bf4c5 in boost::asio::detail::handler_work, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::asio::system_executor>::complete, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code> >(boost::asio::detail::binder1, std::_Placeholder<1>))(boost::system::error_code const&)>, boost::system::error_code>&, std::_Bind, std::_Placeholder<1>))(boost::system::error_code const&)>&) (this=0x7fffdf7fdb6f, function=..., handler=...)
    at /usr/include/boost/asio/detail/handler_work.hpp:82
No locals.

#12 0x00005555557bcecc in boost::asio::detail::wait_handler, std::_Placeholder<1>))(boost::system::error_code const&)> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x555555b08f40, base=0x7fffa8015980) at /usr/include/boost/asio/detail/wait_handler.hpp:72
        b = { = {}, }
        h = 0x7fffa8015980
        p = {h = 0x7fffdf7fdb30, v = 0x0, p = 0x0}
        w = {}
        handler = {
          handler_ = {> = {> = {}, },
            _M_f = (void (i2p::stream::Stream::*)(i2p::stream::Stream * const,
    const boost::system::error_code &)) 0x5555557a9ee8 ,
            _M_bound_args = std::tuple containing = {[1] = std::shared_ptr (use count 4, weak count 1) = {
                get() = 0x7fffa8014b60}, [2] = {> = {}, }}}, arg1_ = {m_val = 0,
            m_cat = 0x7ffff7a00070}}
#13 0x000055555559870a in boost::asio::detail::scheduler_operation::complete (this=0x7fffa8015980, owner=0x555555b08f40, ec=...,
    bytes_transferred=0) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
No locals.
#14 0x000055555559bff9 in boost::asio::detail::scheduler::do_run_one (this=0x555555b08f40, lock=..., this_thread=..., ec=...)
    at /usr/include/boost/asio/detail/impl/scheduler.ipp:401
        task_result = 0
--Type  for more, q to quit, c to continue without paging--
        on_exit = {scheduler_ = 0x555555b08f40, lock_ = 0x7fffdf7fdc80, this_thread_ = 0x7fffdf7fdcb0}
        o = 0x7fffa8015980
        more_handlers = true
#15 0x000055555559bb4a in boost::asio::detail::scheduler::run (this=0x555555b08f40, ec=...)
    at /usr/include/boost/asio/detail/impl/scheduler.ipp:154
        this_thread = { = { = {},
            reusable_memory_ = {0x7fffa8014ac0, 0x0}}, private_op_queue = { = {},
            front_ = 0x0, back_ = 0x0}, private_outstanding_work = 0}
        ctx = { = {}, key_ = 0x555555b08f40, value_ = 0x7fffdf7fdcb0, next_ = 0x0}
        lock = { = {}, mutex_ = @0x555555b08f70, locked_ = false}
        n = 24
#16 0x000055555559c2d7 in boost::asio::io_context::run (this=0x555555b088c8) at /usr/include/boost/asio/impl/io_context.ipp:62
        ec = {m_val = 0, m_cat = 0x7ffff7a00070}
        s = 0
#17 0x000055555576e0e8 in i2p::util::RunnableService::Run (this=0x555555b08890) at libi2pd/util.cpp:98
No locals.
#18 0x000055555576fad4 in std::__invoke_impl (
    __f=@0x555555b09378: (void (i2p::util::RunnableService::*)(i2p::util::RunnableService * const)) 0x55555576e0c0 , __t=@0x555555b09388: 0x555555b08890) at /usr/include/c++/8/bits/invoke.h:73
No locals.
#19 0x000055555576fa4b in std::__invoke (
    __fn=@0x555555b09378: (void (i2p::util::RunnableService::*)(i2p::util::RunnableService * const)) 0x55555576e0c0 , __args#0=@0x555555b09388: 0x555555b08890) at /usr/include/c++/8/bits/invoke.h:95
No locals.
#20 0x000055555576f92a in std::_Bind::__call(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x555555b09378, __args=...) at /usr/include/c++/8/functional:400
No locals.
#21 0x000055555576f78a in std::_Bind::operator()<, void>() (
    this=0x555555b09378) at /usr/include/c++/8/functional:484
No locals.
#22 0x000055555576f611 in std::__invoke_impl>(std::__invoke_other, std::_Bind&&) (__f=...)
    at /usr/include/c++/8/bits/invoke.h:60
No locals.
#23 0x000055555576ebaa in std::__invoke>(std::_Bind&&) (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
No locals.
#24 0x000055555576fb94 in std::thread::_Invoker > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555555b09378) at /usr/include/c++/8/thread:244
No locals.
#25 0x000055555576fb6a in std::thread::_Invoker > >::operator()() (this=0x555555b09378) at /usr/include/c++/8/thread:253
No locals.
#26 0x000055555576fb4e in std::thread::_State_impl > > >::_M_run() (this=0x555555b09370) at /usr/include/c++/8/thread:196
No locals.
#27 0x00007ffff7855b2f in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
--Type  for more, q to quit, c to continue without paging--
#28 0x00007ffff7925fa3 in start_thread (arg=) at pthread_create.c:486
        ret = 
        pd = 
        now = 
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736943089408, -1971596660103066492, 140737488342894, 140737488342895,
                140736943089408, 0, 1971668127258627204, 1971613929073790084}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0},
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 
#29 0x00007ffff75334cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```
tunnels.conf ->
```
[irc-ilita]
type=client
host=127.0.0.1
port=6668
inport=6667
destination=irc.ilita.i2p
inbound.length=0
outbound.length=0
gzip=false
i2cp.leaseSetEncType=0,4
i2cp.leaseSetType=3
keys=transient
```

**Comment by wipedlifepotato** [comment]
thanks
