### ISSUE TITLE
Segfault crash BN_get_flags () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd#1671]
```
Core was generated by `./i2pd_qt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fab8bb66e90 in BN_get_flags () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
[Current thread is 1 (Thread 0x7fab11ffb700 (LWP 3538))]
(gdb) bt full
#0  0x00007fab8bb66e90 in BN_get_flags () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007fab8bb66f83 in BN_free () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x000055f4fd994b00 in DSA_set0_key(dsa_st*, bignum_st*, bignum_st*) (d=0x7faa7005ba80, pub_key=0x7faa700551c0, priv_key=0x0) at libi2pd/Crypto.h:343
#3  0x000055f4fd994d71 in i2p::crypto::DSAVerifier::SetPublicKey(unsigned char const*) (this=0x7faa7005aa80, signingKey=0x7faa7005cbd0 "?T\355\023>\230\273N\030\070\034ɱ+\271{f'\211~D\230\233V\274\351ǖ[w\363\204T\022B\347\352 \217\226\037\350R_\321~\356y\\Dv;^\255&e\212:\310\032\367s\345'n\233\202\035\016\312\362\250d\033wSo\375H\211\231\305\354i\016\005\025\371D\333C\002]M\375\213\005\230\242\272G2\377\346\260\331\312楷\231\024<%1\257\301\326=/![\002\265\255\325\322k") at libi2pd/Signature.h:60
#4  0x000055f4fd9928c9 in i2p::data::IdentityEx::CreateVerifier() const (this=0x7faa7005cad0) at libi2pd/Identity.cpp:382
        keyLen = 128
        verifier = 0x7faa7005aa80
#5  0x000055f4fd992450 in i2p::data::IdentityEx::GetSignatureLen() const (this=0x7faa7005cad0) at libi2pd/Identity.cpp:310
#6  0x000055f4fd9c09dc in i2p::data::RouterInfo::ReadFromBuffer(bool) ()
#7  0x000055f4fd9c0c06 in i2p::data::RouterInfo::RouterInfo(unsigned char const*, int) ()
#8  0x000055f4fd9ff8ac in i2p::data::NetDb::AddRouterInfo(i2p::data::Tag<32ul> const&, unsigned char const*, int, bool&) ()
#9  0x000055f4fd9ffead in i2p::data::NetDb::AddRouterInfo(i2p::data::Tag<32ul> const&, unsigned char const*, int) ()
#10 0x000055f4fda00296 in i2p::data::NetDb::HandleDatabaseStoreMsg(std::shared_ptr<i2p::I2NPMessage const>) ()
#11 0x000055f4fda0059f in i2p::data::NetDb::Run() ()
#12 0x00007fab893856df in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007fab896586db in start_thread (arg=0x7fab11ffb700) at pthread_create.c:463
        pd = 0x7fab11ffb700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140372718106368, -22788282572916541, 140372718104448, 0, 140372281931264, 140372734887168, 70133254840334531, 69833172719188163}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#14 0x00007fab88de071f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

i2pd_qt about box:

img:

![изображение](https://user-images.githubusercontent.com/19966907/123523668-93610b00-d6b4-11eb-8f56-9a959999e7ab.png)

git:

```
git log|head -1
commit d54be50dbf1b26d3f641416e8726b7553c6a63bb
Ok
git remote get-url origin
git@github.com:nonlinear-chaos-order-etc-etal/i2pd-qt.git
Ok
git remote get-url upstream
git@github.com:PurpleI2P/i2pd-qt.git
Ok
git branch
* master
Ok
git push
Total 0 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   git@github.com:nonlin-lin-chaos-order-etc-etal/i2pd-qt.git
To github.com:nonlinear-chaos-order-etc-etal/i2pd-qt.git
   0abe8e5..d54be50  master -> master
Ok
```

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
https://github.com/nonlin-lin-chaos-order-etc-etal/i2pd-qt/commit/d54be50dbf1b26d3f641416e8726b7553c6a63bb

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
```
<eccentric_Turiyya> https://github.com/PurpleI2P/i2pd/issues/1671 orignal я креш отловил
<eccentric_Turiyya> раза 4 сегодня крешалось i2pd-qt
<eccentric_Turiyya> собирал последний i2pd-qt
```

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
```
cat /home/user/.var/app/website.i2pd.i2pd/data/.i2pd/tunnels.conf |grep signature|uniq|sort
signaturetype=1
signaturetype=1
signaturetype=1
signaturetype=7
signaturetype=7
Ok
```
