### ISSUE TITLE
Network status Unknown for SSU2

### ISSUE THREAD

**Issue by Sfinx** [PurpleI2P/i2pd#1773]
```
Uptime: 1 minute, 33 seconds
Network status: Unknown
Network status v6: Unknown
Tunnel creation success rate: 46%
Received: 302.39 KiB (0.00 KiB/s)
Sent: 391.67 KiB (0.00 KiB/s)
Transit: 0.00 KiB (0.00 KiB/s)
Data path: /var/lib/i2pd
Hidden content. Press on text to see.Routers: 927 Floodfills: 507 LeaseSets: 4
Client Tunnels: 70 Transit Tunnels: 0
```

**Comment by r4sas** [comment]
SSU2 in not ready for usage.

**Comment by r4sas** [comment]
8feac310af891ca80938457059806cbf993eb7b2

**Comment by Sfinx** [comment]
> [8feac31](https://github.com/PurpleI2P/i2pd/commit/8feac310af891ca80938457059806cbf993eb7b2)

This commit still prints 'Uknown' in webconsole. BTW: if you forget to disable the ssu when enabling ssu2 you will have additionally the SIGSEGV:

```
12:43:25@342/none - i2pd v2.42.1 (0.9.54) starting...
12:43:25@342/error - RouterInfo: Can't open file 
12:43:26@342/error - Reseed: SU3 verification failed
12:43:27@342/error - Reseed: SU3 verification failed
12:43:27@342/error - Reseed: Failed to connect to reseed2.i2p.net
12:43:28@342/error - Reseed: SU3 verification failed
12:43:28@342/error - Reseed: SU3 verification failed
12:43:28@342/error - Reseed: SU3 verification failed
12:43:29@342/error - Reseed: SU3 verification failed
12:43:30@342/error - Reseed: SU3 verification failed
12:43:30@342/error - Reseed: SU3 verification failed
[New Thread 0x7fbcaddfe640 (LWP 1004983)]
[New Thread 0x7fbcad5fd640 (LWP 1004984)]
[New Thread 0x7fbcacdfc640 (LWP 1004985)]
[New Thread 0x7fbca7fff640 (LWP 1004986)]
[New Thread 0x7fbca77fe640 (LWP 1004987)]
[New Thread 0x7fbca6ffd640 (LWP 1004988)]
[New Thread 0x7fbca67fc640 (LWP 1004989)]
[New Thread 0x7fbca5ffb640 (LWP 1004990)]
12:43:30@342/error - SSU: Failed to bind to v6 port 7990: bind: Address already in use
[New Thread 0x7fbca57fa640 (LWP 1004991)]

Thread 1 "i2pd" received signal SIGSEGV, Segmentation fault.
0x000055b177c836a2 in i2p::transport::Transports::PeerTest(bool, bool) ()
(gdb) backtrace 
#0  0x000055b177c836a2 in i2p::transport::Transports::PeerTest(bool, bool) ()
#1  0x000055b177c876b0 in i2p::transport::Transports::Start(bool, bool, bool) ()
#2  0x000055b177b4b7e5 in i2p::util::Daemon_Singleton::start() ()
#3  0x000055b177bab30d in i2p::util::DaemonLinux::start() ()
#4  0x000055b177b29f43 in main ()
(gdb) 
```

**Comment by r4sas** [comment]
@orignal

**Comment by r4sas** [comment]
No docs because it is not ready...

**Comment by Sfinx** [comment]
Got it. Will wait until it will be ready, thnx !
