### ISSUE TITLE
crash in i2p::data::LeaseSet::SetBuffer

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#1819]
i2p работает у меня на x86_64 openwrt. слинкована с musl.
2.43 нормально все было. на 2.44 начались вылеты.
собрал с debug info, повесил gdb. вот результат

```
Thread 3 "NetDB" received signal SIGILL, Illegal instruction.
[Switching to LWP 29205]
0x000000000041cefe in i2p::data::LeaseSet::SetBuffer(unsigned char const*, unsigned long) [clone .cold.361] ()
(gdb) 

(gdb) bt
#0  0x000000000041cefe in i2p::data::LeaseSet::SetBuffer(unsigned char const*, unsigned long) [clone .cold.361] ()
#1  0x0000000000520f6a in i2p::data::LeaseSet2::LeaseSet2(unsigned char, unsigned char const*, unsigned long, bool, unsigned short) ()
#2  0x000000000053026b in i2p::data::NetDb::AddLeaseSet2(i2p::data::Tag<32ul> const&, unsigned char const*, int, unsigned char) ()
#3  0x00000000005312e7 in i2p::data::NetDb::HandleDatabaseStoreMsg(std::shared_ptr<i2p::I2NPMessage const>) ()
#4  0x000000000053295c in i2p::data::NetDb::Run() ()
#5  0x00007ffff7b1ee84 in ?? () from /usr/lib/libstdc++.so.6
#6  0x00007ffff7fdd15e in ?? () from /lib/ld-musl-x86_64.so.1
#7  0x0000000000000000 in ?? ()

(gdb) p /x $rip
$2 = 0x41cefe

(gdb) x /2bx $rip
0x41cefe <_ZN3i2p4data8LeaseSet9SetBufferEPKhm.cold.361>:       0x0f    0x0b

```

```
.text:000000000041CEFE                         ; i2p::data::LeaseSet::SetBuffer(unsigned char const*, unsigned long) [clone]
.text:000000000041CEFE                         _ZN3i2p4data8LeaseSet9SetBufferEPKhm_cold_361 proc near
.text:000000000041CEFE                                                                 ; CODE XREF: i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)+3B↓j
.text:000000000041CEFE                                                                 ; i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)+4E↓j
.text:000000000041CEFE                         ; __unwind {
.text:000000000041CEFE 0F 0B                                   ud2
.text:000000000041CEFE                         ; } // starts at 41CEFE

```

**Comment by bol-van** [comment]
Отсюда идет вызов SetBuffer
```
.text:0000000000520F64 67 E8 26 B7 FF FF                       call    _ZN3i2p4data8LeaseSet9SetBufferEPKhm ; i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)
.text:0000000000520F6A 41 80 FD 05                             cmp     r13b, 5
.text:0000000000520F6E 74 30                                   jz      short loc_520FA0

```

Сам SetBuffer

```
.text:000000000051C690                         ; _QWORD __fastcall i2p::data::LeaseSet::SetBuffer(i2p::data::LeaseSet *__hidden this, const unsigned __int8 *, unsigned __int64)
.text:000000000051C690                                         public _ZN3i2p4data8LeaseSet9SetBufferEPKhm
.text:000000000051C690                         _ZN3i2p4data8LeaseSet9SetBufferEPKhm proc near
.text:000000000051C690                                                                 ; CODE XREF: i2p::data::LeaseSet2::Update(uchar const*,ulong,bool)+16↓p
.text:000000000051C690                                                                 ; i2p::data::LeaseSet2::ReadFromBufferEncrypted(uchar const*,ulong,std::shared_ptr<i2p::data::BlindedPublicKey const>,uchar const*)+568↓p ...
.text:000000000051C690                         ; __unwind {
.text:000000000051C690 41 54                                   push    r12
.text:000000000051C692 49 89 FC                                mov     r12, rdi
.text:000000000051C695 55                                      push    rbp
.text:000000000051C696 48 89 F5                                mov     rbp, rsi
.text:000000000051C699 53                                      push    rbx
.text:000000000051C69A 48 8B 7F 60                             mov     rdi, [rdi+60h]  ; void *
.text:000000000051C69E 48 89 D3                                mov     rbx, rdx
.text:000000000051C6A1 48 85 FF                                test    rdi, rdi
.text:000000000051C6A4 74 06                                   jz      short loc_51C6AC
.text:000000000051C6A6 FF 15 5C 82 26 00                       call    cs:_ZdaPv_ptr   ; operator delete[](void *)
.text:000000000051C6AC
.text:000000000051C6AC                         loc_51C6AC:                             ; CODE XREF: i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)+14↑j
.text:000000000051C6AC 48 89 DF                                mov     rdi, rbx        ; unsigned __int64
.text:000000000051C6AF FF 15 F3 76 26 00                       call    cs:_Znam_ptr    ; operator new[](ulong)
.text:000000000051C6B5 49 89 5C 24 68                          mov     [r12+68h], rbx
.text:000000000051C6BA 49 89 44 24 60                          mov     [r12+60h], rax
.text:000000000051C6BF 48 39 E8                                cmp     rax, rbp
.text:000000000051C6C2 73 0D                                   jnb     short loc_51C6D1
.text:000000000051C6C4 48 8D 14 18                             lea     rdx, [rax+rbx]
.text:000000000051C6C8 48 39 D5                                cmp     rbp, rdx
.text:000000000051C6CB 0F 82 2D 08 F0 FF                       jb      _ZN3i2p4data8LeaseSet9SetBufferEPKhm_cold_361 ; i2p::data::LeaseSet::SetBuffer(uchar const*,ulong) [clone]
.text:000000000051C6D1
.text:000000000051C6D1                         loc_51C6D1:                             ; CODE XREF: i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)+32↑j
.text:000000000051C6D1 48 39 E8                                cmp     rax, rbp
.text:000000000051C6D4 76 0E                                   jbe     short loc_51C6E4
.text:000000000051C6D6 48 8D 54 1D 00                          lea     rdx, [rbp+rbx+0]
.text:000000000051C6DB 48 39 D0                                cmp     rax, rdx
.text:000000000051C6DE 0F 82 1A 08 F0 FF                       jb      _ZN3i2p4data8LeaseSet9SetBufferEPKhm_cold_361 ; i2p::data::LeaseSet::SetBuffer(uchar const*,ulong) [clone]
.text:000000000051C6E4
.text:000000000051C6E4                         loc_51C6E4:                             ; CODE XREF: i2p::data::LeaseSet::SetBuffer(uchar const*,ulong)+44↑j
.text:000000000051C6E4 48 89 DA                                mov     rdx, rbx        ; n
.text:000000000051C6E7 48 89 EE                                mov     rsi, rbp        ; src
.text:000000000051C6EA 5B                                      pop     rbx
.text:000000000051C6EB 48 89 C7                                mov     rdi, rax        ; dest
.text:000000000051C6EE 5D                                      pop     rbp
.text:000000000051C6EF 41 5C                                   pop     r12
.text:000000000051C6F1 FF 25 F1 81 26 00                       jmp     cs:memcpy_ptr
.text:000000000051C6F1                         ; } // starts at 51C690
.text:000000000051C6F1                         _ZN3i2p4data8LeaseSet9SetBufferEPKhm endp

```

Переходы _ZN3i2p4data8LeaseSet9SetBufferEPKhm_cold_361  ведут на undefined instruction  по адресу 41CEFE

**Comment by bol-van** [comment]
```
	void LeaseSet::SetBuffer (const uint8_t * buf, size_t len)
	{
		if (m_Buffer) delete[] m_Buffer;
		m_Buffer = new uint8_t[len];
		m_BufferLen = len;
		memcpy (m_Buffer, buf, len);
	}
```

```
(gdb) p /x $rbx
$4 = 0x90a5
(gdb) p /x $rax
$5 = 0x44c1840
(gdb) p /x $rbp
$6 = 0x44ba53b
(gdb) p /x $r12
$7 = 0x2f03690

```

Перед memcpy компилятор вставляет проверку на непересечение буферов, и она проваливается

**Comment by orignal** [comment]
Это в 2.44 не меняли. Будем разбираться.

**Comment by Vort** [comment]
После 2.44 было много исправлений.
В том числе, относящееся к LeaseSet: 9e02c99db50394d9f4c453d77c119e6aa9a671b3
Думаю, для тестов стоит собирать самую последнюю версию.

**Comment by bol-van** [comment]
> Это в 2.44 не меняли. Будем разбираться.

В этом месте не меняли, но buf то откуда-то приходит

**Comment by orignal** [comment]
Как заметили выше, эту проблему уже чинили, но после 2.44

**Comment by dbzoo** [comment]
FreeBSD 12.2 (crashing roughly the same location)

Core was generated by `/usr/local/bin/i2pd --bandwidth X --share 80 --port 10123 --http.address=0.0.0.0'.
Program terminated with signal SIGSEGV, Segmentation fault.
Address not mapped to object.
#0  0x0000000800e08cea in memcpy () from /lib/libc.so.7
[Current thread is 1 (LWP 101526)]
(gdb) bt
#0  0x0000000800e08cea in memcpy () from /lib/libc.so.7
#1  0x000000000040e4bc in i2p::data::LeaseSet2::LeaseSet2(unsigned char, unsigned char const*, unsigned long, bool, unsigned short) ()
#2  0x0000000000422c9e in i2p::data::NetDb::AddLeaseSet2(i2p::data::Tag<32ul> const&, unsigned char const*, int, unsigned char) ()
#3  0x000000000041c65c in i2p::data::NetDb::HandleDatabaseStoreMsg(std::__1::shared_ptr<i2p::I2NPMessage const>) ()
#4  0x000000000041b49c in i2p::data::NetDb::Run() ()
#5  0x0000000000435bfd in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (i2p::data::NetDb::*)(), i2p::data::NetDb*> > >(void*) ()
#6  0x0000000800c2f08c in ?? () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()

**Comment by orignal** [comment]
Так попробуйте текущий собрать

**Comment by r4sas** [comment]
Please test with 2.45.0
