### ISSUE TITLE
Crash in HTTP headers parsing when accessing HTTP console

### ISSUE THREAD

**Issue by AMDmi3** [PurpleI2P/i2pd#501]
FreeBSD 10.3 amd64, when trying to access console (127.0.0.1:7070) with elinks, i2pd crashes:

```
[New Thread 805c06c00 (LWP 100109/i2pd)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 805c06c00 (LWP 100109/i2pd)]
0x0000000802d3d35a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x0000000802d3d35a in thr_kill () from /lib/libc.so.7
#1  0x0000000802d3d346 in raise () from /lib/libc.so.7
#2  0x0000000802d3d2c9 in abort () from /lib/libc.so.7
#3  0x0000000802418839 in __cxa_rethrow () from /lib/libcxxrt.so.1
#4  0x0000000800f31187 in std::__1::__basic_string_common<true>::__throw_out_of_range () from /usr/local/lib/libboost_filesystem.so.1.55.0
#5  0x00000008021d3c45 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at () from /usr/lib/libc++.so.1
#6  0x00000000007ab747 in i2p::http::parse_header_line (line=@0x7fffdfffcef8, headers=@0x7fffdfffd568) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTP.cpp:49
#7  0x00000000007b4052 in i2p::http::HTTPReq::parse (this=0x7fffdfffd568, str=@0x7fffdfffd548) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTP.cpp:221
#8  0x0000000000461b12 in i2p::http::HTTPConnection::RunRequest (this=0x80615c018) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTPServer.cpp:696
#9  0x000000000046198d in i2p::http::HTTPConnection::HandleReceive (this=0x80615c018, ecode=@0x7fffdfffda88, bytes_transferred=196) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTPServer.cpp:689
#10 0x0000000000480373 in _ZN5boost4asio6detail7binder2INSt3__16__bindIMN3i2p4http14HTTPConnectionEFvRKNS_6system10error_codeEmEJNS3_10shared_ptrIS7_EERNS3_12placeholders4__phILi1EEERNSH_ILi2EEEEEES9_mEclEv (this=0x7fffdfffda68) at __functional_base:380
#11 0x00000000004800a9 in _ZN5boost4asio19asio_handler_invokeINS0_6detail7binder2INSt3__16__bindIMN3i2p4http14HTTPConnectionEFvRKNS_6system10error_codeEmEJNS4_10shared_ptrIS8_EERNS4_12placeholders4__phILi1EEERNSI_ILi2EEEEEESA_mEEEEvRT_z (
    function=@0x7fffdfffda68) at handler_invoke_hook.hpp:69
#12 0x000000000047ff57 in _ZN33boost_asio_handler_invoke_helpers6invokeIN5boost4asio6detail7binder2INSt3__16__bindIMN3i2p4http14HTTPConnectionEFvRKNS1_6system10error_codeEmEJNS5_10shared_ptrIS9_EERNS5_12placeholders4__phILi1EEERNSJ_ILi2EEEEEESB_mEESO_EEvRT_RT0_
    (function=@0x7fffdfffda68, context=@0x7fffdfffda68) at handler_invoke_helpers.hpp:37
#13 0x000000000047fd67 in _ZN5boost4asio6detail23reactive_socket_recv_opINS0_17mutable_buffers_1ENSt3__16__bindIMN3i2p4http14HTTPConnectionEFvRKNS_6system10error_codeEmEJNS4_10shared_ptrIS8_EERNS4_12placeholders4__phILi1EEERNSI_ILi2EEEEEEE11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationESC_m (owner=0x805cddd40, base=0x805cddde0) at reactive_socket_recv_op.hpp:110
#14 0x0000000000491067 in boost::asio::detail::task_io_service_operation::complete (this=0x805cddde0, owner=@0x805cddd40, ec=@0x7fffdfffdd08, bytes_transferred=0) at task_io_service_operation.hpp:38
#15 0x0000000000490435 in boost::asio::detail::task_io_service::do_run_one (this=0x805cddd40, lock=@0x7fffdfffdc20, this_thread=@0x7fffdfffdc68, ec=@0x7fffdfffdd08) at task_io_service.ipp:384
#16 0x000000000048fedd in boost::asio::detail::task_io_service::run (this=0x805cddd40, ec=@0x7fffdfffdd08) at task_io_service.ipp:153
#17 0x000000000046df21 in boost::asio::io_service::run (this=0x805c163c8) at io_service.ipp:59
#18 0x00000000004682cc in i2p::http::HTTPServer::Run (this=0x805c163c0) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTPServer.cpp:911
#19 0x0000000000476349 in _ZNSt3__114__thread_proxyINS_5tupleIJNS_6__bindIMN3i2p4http10HTTPServerEFvvEJPS5_EEEEEEEEPvSB_ (__vp=0x805e85c40) at __functional_base:380
#20 0x0000000802a61855 in pthread_create () from /lib/libthr.so.3
#21 0x0000000000000000 in ?? ()
(gdb) frame 6
#6  0x00000000007ab747 in i2p::http::parse_header_line (line=@0x7fffdfffcef8, headers=@0x7fffdfffd568) at /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTP.cpp:49
49      /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTP.cpp: No such file or directory.
        in /home/amdmi3/i2pd/work/i2pd-2.7.0/HTTP.cpp
(gdb) print pos
$1 = 15
(gdb) print len
$2 = 2
(gdb) print line
$3 = (const string &) @0x7fffdfffcef8: {<std::__1::__basic_string_common<true>> = {<No data fields>}, 
  __r_ = {<std::__1::__libcpp_compressed_pair_imp<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, std::__1::allocator<char>, 2>> = {<std::__1::allocator<char>> = {<No data fields>}, __first_ = {{__l = {
            __cap_ = 3275366409766650146, __size_ = 7453010313431182917, __data_ = 0x80500203a ""}, __s = {{__size_ = 34 '"', __lx = 34 '"'}, __data_ = "Accept-Encoding: \000\005\b\000\000"}, __r = {__words = {3275366409766650146, 7453010313431182917, 
              34443632698}}}}}, <No data fields>}, static npos = <optimized out>}
```

**Comment by AMDmi3** [comment]
This code seem to need range checking as it'll fail on any header with empty value.
