### ISSUE TITLE
Refreshing "Transports" page of i2pd webconsole leads to server termination

### ISSUE THREAD

**Issue by uaply** [PurpleI2P/i2pd#629]
Hard-to-reproduce error can occur during opening of "Transports" page of webconsole

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected
Aborted
```

Steps to reproduce:
run stress-test with apache ab tool

```
ab -c 5 -n 1000 http://127.0.0.1:7070/?page=transports
```

But most of the times nothing bad happens.

Probably caused by this line:
https://github.com/PurpleI2P/i2pd/blob/722f1c4430c30ed2643c3dd2e3dc60c1782c5009/HTTPServer.cpp#L464
analogous to https://github.com/nghttp2/nghttp2/commit/2d6211c45552252864f7afa71d7634cbf1e2f9d0

**Comment by orignal** [comment]
But easy to fix

**Comment by uaply** [comment]
Other places where remote_endpoint() is called should be inspected also.

**Comment by orignal** [comment]
It's handled properly everywhere else.

**Comment by uaply** [comment]
Still possible to make it fail, in different place:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x08085cc2 in i2p::transport::NTCPSession::IsEstablished (this=0x81ebd2e8) at NTCPSession.h:57
#1  0x0807a134 in i2p::http::ShowTransports (s=...) at HTTPServer.cpp:460
#2  0x0807c10e in i2p::http::HTTPConnection::HandlePage (this=0xb43efb98, req=..., res=..., s=...) at HTTPServer.cpp:691
#3  0x0807be58 in i2p::http::HTTPConnection::HandleRequest (this=0xb43efb98, req=...) at HTTPServer.cpp:666
#4  0x0807b80a in i2p::http::HTTPConnection::RunRequest (this=0xb43efb98) at HTTPServer.cpp:611
#5  0x0807b749 in i2p::http::HTTPConnection::HandleReceive (this=0xb43efb98, ecode=..., bytes_transferred=98) at HTTPServer.cpp:595
```

**Comment by orignal** [comment]
That's different issue.

**Comment by r4sas** [comment]
Any updates?
Can anyone check this?

**Comment by r4sas** [comment]
Closing due to inactivity.
