### ISSUE TITLE
I2PControl implementation broken

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#767]
itoopie returns error (INTERNAL ERROR) when trying to connect to i2pd i2pcontrol:

    {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}

Full error message is

    jan 05, 2017 5:46:54 EM net.i2p.itoopie.configuration.ConfigurationManager readConfFile
    INFO: Unable to find config file, /home/user/.itoopie/itoopie.conf
    Request: {"method":"RouterInfo","id":-1611875601,"params": {"i2p.router.net.tunnels.participating":null,"Token":null},"jsonrpc":"2.0"}
    Response: {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}
    jan 05, 2017 5:47:00 EM net.i2p.itoopie.i2pcontrol.JSONRPC2Interface sendReq
    FATAL: Remote host: <unspecified file>(1): expected object or array
    Exception in thread "Thread-6" java.lang.NullPointerException
	at net.i2p.itoopie.gui.component.chart.ParticipatingTunnelsTracker.runOnce(ParticipatingTunnelsTracker.java:55)
	at net.i2p.itoopie.gui.component.chart.ParticipatingTunnelsTracker.run(ParticipatingTunnelsTracker.java:41)
    Request: {"method":"RouterInfo","id":-1611875600,"params":{"i2p.router.net.bw.outbound.1s":null,"Token":null},"jsonrpc":"2.0"}
    Response: {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}
    jan 05, 2017 5:47:00 EM net.i2p.itoopie.i2pcontrol.JSONRPC2Interface sendReq
    FATAL: Remote host: <unspecified file>(1): expected object or array
    Exception in thread "Thread-3" java.lang.NullPointerException
	at net.i2p.itoopie.gui.component.chart.OutboundBandwidthTracker.runOnce(OutboundBandwidthTracker.java:55)
	at net.i2p.itoopie.gui.component.chart.OutboundBandwidthTracker.run(OutboundBandwidthTracker.java:42)
    Request: {"method":"RouterInfo","id":-1611875602,"params":{"i2p.router.net.bw.inbound.1s":null,"Token":null},"jsonrpc":"2.0"}
    Response: {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}
    jan 05, 2017 5:47:00 EM net.i2p.itoopie.i2pcontrol.JSONRPC2Interface sendReq
    FATAL: Remote host: <unspecified file>(1): expected object or array
    Request: {"method":"RouterInfo","id":-1611875599,"params":{"i2p.router.status":null,"Token":null,"i2p.router.uptime":null,"i2p.router.net.status":null,"i2p.router.version":null},"jsonrpc":"2.0"}
    Exception in thread "Thread-2" Response: {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}
    java.lang.NullPointerException
	at net.i2p.itoopie.gui.component.chart.InboundBandwidthTracker.runOnce(InboundBandwidthTracker.java:55)
	at net.i2p.itoopie.gui.component.chart.InboundBandwidthTracker.run(InboundBandwidthTracker.java:42)
    jan 05, 2017 5:47:00 EM net.i2p.itoopie.i2pcontrol.JSONRPC2Interface sendReq
    FATAL: Remote host: <unspecified file>(1): expected object or array
    java.lang.NullPointerException
	at net.i2p.itoopie.gui.OverviewTab.populateInfo(OverviewTab.java:147)
	at net.i2p.itoopie.gui.OverviewTab.access$000(OverviewTab.java:33)
	at net.i2p.itoopie.gui.OverviewTab$1.run(OverviewTab.java:131)
    Request: {"method":"RouterInfo","id":-1611875598,"params":{"i2p.router.status":null,"Token":null,"i2p.router.uptime":null,"i2p.router.net.status":null,"i2p.router.version":null},"jsonrpc":"2.0"}
    Response: {"id":null,"error":{"code":-32603,"message":"<unspecified file>(1): expected object or array"},"jsonrpc":"2.0"}
    jan 05, 2017 5:47:00 EM net.i2p.itoopie.i2pcontrol.JSONRPC2Interface sendReq
    FATAL: Remote host: <unspecified file>(1): expected object or array
    java.lang.NullPointerException
	at net.i2p.itoopie.gui.OverviewTab.populateInfo(OverviewTab.java:147)
	at net.i2p.itoopie.gui.OverviewTab.onTabFocus(OverviewTab.java:170)
	at net.i2p.itoopie.gui.component.util.TabChangeListener$1.run(TabChangeListener.java:34)

**Comment by mathiasfriman** [comment]
Good work guys. Latest pull from git solves the problem :)
