### ISSUE TITLE
Absence of SIGPIPE handler = bad bug?

### ISSUE THREAD

**Issue by pwrml** [PurpleI2P/i2pd#833]
Does i2pd have any SIGPIPE handler??

If not, that should be a bad bug.

More discussion here http://www.tedunangst.com/flak/post/SIGPIPE-can-happen-to-you .

Suspect this is the cause for https://github.com/PurpleI2P/i2pd/issues/830 .

**Comment by orignal** [comment]
Will add this handler

**Comment by pwrml** [comment]
Great. Just for your reference, one of my sigpipes were trigged here. Anyhow, yeah your fix looks like it does it. Thanks!

```
07:57:24@787/warn - TunnelMessage: I2NP message size 1078 is not enough

Program received signal SIGPIPE, Broken pipe.
[Switching to thread 1072128]
0x0000135ddc46989a in _thread_sys_sendmsg () at <stdin>:2
2       <stdin>: No such file or directory.
        in <stdin>
Current language:  auto; currently asm
(gdb)
(gdb)
(gdb) bt
#0  0x0000135ddc46989a in _thread_sys_sendmsg () at <stdin>:2
#1  0x0000135ddc44dc47 in *_libc_sendmsg_cancel (s=Variable "s" is not available.
) at /usr/src/lib/libc/sys/w_sendmsg.c:27
#2  0x0000135bb1f6cf77 in boost::asio::detail::socket_ops::send () from /home/MYUSER/i2pd/build/i2pd
#3  0x0000135bb1f6d01c in boost::asio::detail::socket_ops::non_blocking_send () from /home/MYUSER/i2pd/build/i2pd
#4  0x0000135bb2137046 in boost::asio::detail::reactive_socket_send_op_base<boost::asio::detail::consuming_buffers<boost::asio::const_buffer, std::vector<boost::asio::const_buffer, std::allocator<boost::asio::const_buffer> > > >::do_perform () from /home/MYUSER/i2pd/build/i2pd
#5  0x0000135bb1f693f3 in boost::asio::detail::reactor_op::perform () from /home/MYUSER/i2pd/build/i2pd
#6  0x0000135bb1f6acdc in boost::asio::detail::kqueue_reactor::run () from /home/MYUSER/i2pd/build/i2pd
#7  0x0000135bb1f6bc71 in boost::asio::detail::task_io_service::do_run_one () from /home/MYUSER/i2pd/build/i2pd
#8  0x0000135bb1f6b7ac in boost::asio::detail::task_io_service::run () from /home/MYUSER/i2pd/build/i2pd
#9  0x0000135bb1f6bff8 in boost::asio::io_service::run () from /home/MYUSER/i2pd/build/i2pd
#10 0x0000135bb2111835 in i2p::transport::NTCPServer::Run () from /home/MYUSER/i2pd/build/i2pd
#11 0x0000135bb213a99d in _ZNKSt7_Mem_fnIMN3i2p9transport10NTCPServerEFvvEEclIJEvEEvPS2_DpOT_ () from /home/MYUSER/i2pd/build/i2pd
#12 0x0000135bb213a8fb in _ZNSt5_BindIFSt7_Mem_fnIMN3i2p9transport10NTCPServerEFvvEEPS3_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE ()
   from /home/MYUSER/i2pd/build/i2pd
#13 0x0000135bb213a84f in _ZNSt5_BindIFSt7_Mem_fnIMN3i2p9transport10NTCPServerEFvvEEPS3_EEclIJEvEET0_DpOT_ () from /home/MYUSER/i2pd/build/i2pd
#14 0x0000135bb213a796 in _ZNSt12_Bind_simpleIFSt5_BindIFSt7_Mem_fnIMN3i2p9transport10NTCPServerEFvvEEPS4_EEvEE9_M_invokeIJEEEvSt12_Index_tupleIJXspT_EEE () from /home/MYUSER/i2pd/build/i2pd
#15 0x0000135bb213a66a in std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::transport::NTCPServer::*)()> ()(i2p::transport::NTCPServer*)> ()()>::operator() ()
   from /home/MYUSER/i2pd/build/i2pd
#16 0x0000135bb213a576 in std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::transport::NTCPServer::*)()> ()(i2p::transport::NTCPServer*)> ()()> >::_M_run ()
   from /home/MYUSER/i2pd/build/i2pd
Die: DW_TAG_unspecified_type (abbrev = 111, offset = 2137427)
        has children: FALSE
        attributes:
                DW_AT_name (DW_FORM_strp) string: "decltype(nullptr)"
Dwarf Error: Cannot find type of die [in module /usr/local/lib/libestdc++.so.17.0]
```
