### ISSUE TITLE
Unexpected segmentation faults

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#931]
i2pd ver 2.15
Debian Jessie 64-bit (2 очень похожие VDS, оставшихся от неудачных опытов с IPv6 https://github.com/PurpleI2P/i2pd/issues/851 )
Упали с разницей в полчаса, у хостера в этот день были некие "проблемы на линии".
Не исключаю, что это как-то связано с https://github.com/PurpleI2P/i2pd/issues/867
```
~# gdb -e /usr/sbin/i2pd -c /var/lib/i2pd/core_a -s /usr/lib/debug/.build-id/a0/ee497ae7320d5be0007a463ca263d4973aa47a.debug
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/debug/.build-id/a0/ee497ae7320d5be0007a463ca263d4973aa47a.debug...done.
[New LWP 18799]
[New LWP 18787]
[New LWP 18788]
[New LWP 18794]
[New LWP 18796]
[New LWP 18797]
[New LWP 18800]
[New LWP 19200]
[New LWP 18795]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/i2pd --service --daemon --log=file --logfile=/var/log/i2pd/i2pd.log -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000054f6e2 in memcpy (__len=256, __src=0x8, __dest=0x7f0a017f98d5) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
51        return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
(gdb) bt
#0  0x000000000054f6e2 in memcpy (__len=256, __src=0x8, __dest=0x7f0a017f98d5) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
#1  i2p::transport::SSUSession::SendSessionCreated (this=0x7f09f80e2dd0, this@entry=0x7f0a017f9730, x=<optimized out>,
    sendRelayTag=sendRelayTag@entry=true) at libi2pd/SSUSession.cpp:436
#2  0x000000000054fd8f in i2p::transport::SSUSession::ProcessSessionRequest (this=0x7f0a017f9730, buf=0x8605c0 <i2p::context> "\220\270\205",
    len=<error reading variable: can't compute CFA for this frame>, senderEndpoint=...) at libi2pd/SSUSession.cpp:222
#3  0x9a4cb888106c1bce in ?? ()
#4  0x0000000000000130 in ?? ()
#5  0x82b1a8b603729c15 in ?? ()
#6  0x0000000000000028 in ?? ()
#7  0x0000000000000000 in ?? ()
(gdb) info threads
  Id   Target Id         Frame
  9    Thread 0x7f0a037fe700 (LWP 18795) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f0a007f8700 (LWP 19200) bn_sqr8x_internal () at x86_64-mont5.s:1757
  7    Thread 0x7f0a00ff9700 (LWP 18800) 0x00007f0a08e2ac03 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7f0a027fc700 (LWP 18797) 0x00007f0a0991849b in pthread_join (threadid=139680934758144, thread_return=0x0) at pthread_join.c:92
  5    Thread 0x7f0a02ffd700 (LWP 18796) 0x00007f0a08e2ac03 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  4    Thread 0x7f0a03fff700 (LWP 18794) pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  3    Thread 0x7f0a08935700 (LWP 18788) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f0a0aecb740 (LWP 18787) 0x00007f0a0991849b in pthread_join (threadid=139680951543552, thread_return=0x0) at pthread_join.c:92
* 1    Thread 0x7f0a017fa700 (LWP 18799) 0x000000000054f6e2 in memcpy (__len=256, __src=0x8, __dest=0x7f0a017f98d5)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:51
(gdb)
```

```
~# gdb -e /usr/sbin/i2pd -c /var/lib/i2pd/core_a -s /usr/lib/debug/.build-id/a0/ee497ae7320d5be0007a463ca263d4973aa47a.debug
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/debug/.build-id/a0/ee497ae7320d5be0007a463ca263d4973aa47a.debug...done.
[New LWP 892]
[New LWP 756]
[New LWP 891]
[New LWP 894]
[New LWP 895]
[New LWP 896]
[New LWP 989]
[New LWP 890]
[New LWP 754]
[New LWP 893]

warning: Error reading shared library list entry at 0x1

warning: Corrupted shared library list: 0x0 != 0x1
Core was generated by `/usr/sbin/i2pd --service --daemon --log=file --logfile=/var/log/i2pd/i2pd.log -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fccda493b63 in ?? ()
(gdb) bt
#0  0x00007fccda493b63 in ?? ()
#1  0x9ef2e44ac3724981 in ?? ()
#2  0x000000000085d840 in ?? ()
#3  0xcb3ac1d6ca62c1d6 in ?? ()
#4  0xcab1c1d6cde3a1d6 in ?? ()
#5  0xd170c1d6ca62c1d6 in ?? ()
#6  0x00007fccbc000020 in ?? ()
#7  0x00000000000007b0 in ?? ()
#8  0x00007fccbc089f98 in ?? ()
#9  0x0000000001a066a0 in ?? ()
#10 0x00000000000007a8 in ?? ()
#11 0x00007fccd880abd0 in ?? ()
#12 0x00007fccda494e98 in ?? ()
#13 0x98b8546b0000004e in ?? ()
#14 0x4ffbb06adcc169ae in ?? ()
#15 0xf533bfc76e18f865 in ?? ()
#16 0xbe054995d2cc806c in ?? ()
#17 0xe38aeb7d8cf7156d in ?? ()
#18 0x1ba5360c52b3a7e6 in ?? ()
#19 0x00007fccd880a9e0 in ?? ()
#20 0x00007fccd880aa08 in ?? ()
#21 0x00007fccd880aa48 in ?? ()
#22 0x00007fccd880a988 in ?? ()
#23 0x00007fccd880aaa0 in ?? ()
#24 0x00000000000002b9 in ?? ()
#25 0x00007fccd880aa3a in ?? ()
#26 0x00007fccbc000020 in ?? ()
#27 0x00000000000007a8 in ?? ()
#28 0x00007fccbc089f98 in ?? ()
#29 0x0000000001a066a0 in ?? ()
#30 0x000000000085d8a8 in vtable for std::_Sp_counted_ptr_inplace<i2p::client::I2PServerTunnelConnectionHTTP, std::allocator<i2p::client::I2PServerTunnelConnectionHTTP>, (__gnu_cxx::_Lock_policy)2> ()
#31 0x00007fccd880abd0 in ?? ()
#32 0x00007fccda497020 in ?? ()
#33 0x0000000000000002 in ?? ()
#34 0x00000000000007a8 in ?? ()
#35 0x00007fccd880aa90 in ?? ()
#36 0x00007fccdad3c2e8 in ?? ()
#37 0x00000000e7073254 in ?? ()
#38 0x00000000004b92dc in __copy_m<std::shared_ptr<i2p::crypto::DHKeys>*> (__result=0x7fccbc172510, __last=<optimized out>, __first=<optimized out>) at /usr/include/c++/4.9/bits/stl_algobase.h:378
#39 __copy_move_a<false, std::shared_ptr<i2p::crypto::DHKeys>**, std::shared_ptr<i2p::crypto::DHKeys>**> (__result=0x7fccbc172510, __last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_algobase.h:396
#40 __copy_move_a2<false, std::shared_ptr<i2p::crypto::DHKeys>**, std::shared_ptr<i2p::crypto::DHKeys>**> (__result=0x7fccbc172510, __last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_algobase.h:434
#41 copy<std::shared_ptr<i2p::crypto::DHKeys>**, std::shared_ptr<i2p::crypto::DHKeys>**> (__result=0x7fccbc172510, __last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_algobase.h:466
#42 _M_reallocate_map (__add_at_front=false, __nodes_to_add=1, this=0x7fccbc009c10) at /usr/include/c++/4.9/bits/deque.tcc:909
#43 _M_reserve_map_at_back (__nodes_to_add=1, this=0x7fccbc009c10) at /usr/include/c++/4.9/bits/stl_deque.h:2000
#44 std::deque<std::shared_ptr<i2p::crypto::DHKeys>, std::allocator<std::shared_ptr<i2p::crypto::DHKeys> > >::_M_push_back_aux<std::shared_ptr<i2p::crypto::DHKeys> const&> (this=0x7fccbc009c10)
    at /usr/include/c++/4.9/bits/deque.tcc:451
#45 0x000000770000006e in ?? ()
#46 0x0000000000000000 in ?? ()
(gdb) info threads
  Id   Target Id         Frame
  10   LWP 893           0x00007fccdc00dcac in ?? ()
  9    LWP 754           0x0000000000440e73 in virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::bad_cast> >::clone() const ()
    at /usr/include/boost/exception/exception.hpp:458
  8    LWP 890           0x00007fccdaff685a in ?? ()
  7    LWP 989           0x00007fccdaff404f in ?? ()
  6    LWP 896           0x00007fccda503c03 in ?? ()
  5    LWP 895           0x00007fccda503c03 in ?? ()
  4    LWP 894           0x00007fccda503c03 in ?? ()
  3    LWP 891           0x00007fccdaff404f in ?? ()
  2    LWP 756           0x00007fccdaff404f in ?? ()
* 1    LWP 892           0x00007fccda493b63 in ?? ()
(gdb)
```

**Comment by orignal** [comment]
Вот теперь наконец стало понятно в чем дело
